name: Security
on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - .yarn/cache
      - .yarnrc
      - yarn.lock
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - run: yarn install --immutable --immutable-cache --check-cache
