name: Security
on:
  pull_request:
    types:
      - opened
      - synchronize
    paths-ignore:
      - .yarn/cache
      - .yarnrc
      - yarn.lock
jobs:
  packages:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'No package check needed'
